# _config.yml
title: Broke Consortium of Mathematical Research
description: English site for the Broke Consortium
baseurl: ""
url: "https://brokeconsortium.github.io"
author:
  name: "Aitzaz Imtiaz"
  email: "aitzazimtiaz@brokeconsortium.re.kr"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-picture-tag
  - jekyll-include-cache
  - jekyll-paginate-v2
  - jekyll-typogrify

exclude:
  - Gemfile

seo:
  title: "Broke Consortium"
  description: "English site for the Broke Consortium"
  github_username: "brokeconsortium"

timezone: "Asia/Seoul"
language: "en"

include_cache:
  enabled: true

typogrify:
  enable: true
  smart_quotes: true
  smart_dashes: true
  ellipses: true
  caps: true
